version: 0.2

phases:
  build:
    commands:
      - make archive

  post_build:
    commands:
      - sam package --output-template-file packaged.yaml --s3-bucket $S3BUCKET
      - aws s3 cp ./packaged.yaml $S3BUCKET/packaged.yaml