version: 0.2

phases:
  pre_build:
    commands:
      - echo Target Bucket $S3BUCKET

  build:
    commands:
      - make archive

  post_build:
    commands:
      - sam package --output-template-file packaged.yaml --s3-bucket $S3BUCKET
      - aws s3 cp ./packaged.yaml s3://$S3BUCKET/packaged.yaml