AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  BucketName:
    Type: String
    Default: Name of bucket to add event too.
  LambdaExportName:
    Type: String
    Description: The exported name of the lambda to trigger from the original stack.
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      NotificationConfiguration:
        LambdaConfigurations:
        - Event: "s3:ObjectCreated:Put"
          Function:
            Fn::ImportValue: !Ref LambdaExportName